language: python
  python:
    - "3.6"
# command to install dependencies
install:
  - pip install -r python/01/requirements.txt
script:
  - cd python/01 && pytest
notifications:
  email:
    recipients:
      - juzerali@gmail.com
    on_success: never # default: change
    on_failure: never # default: always